# Generated by Django 4.0.3 on 2022-11-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_writingrecord_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingrecord',
            name='features',
            field=models.TextField(blank=True, verbose_name='features'),
        ),
    ]
