# Generated by Django 4.0.3 on 2022-11-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0006_teacherstudentrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingexam',
            name='time',
            field=models.IntegerField(default=60, verbose_name='minutes for this exam'),
        ),
    ]
