# Generated by Django 4.0.3 on 2022-11-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0007_writingexam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingrecord',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='score'),
        ),
    ]
