# Generated by Django 4.0.3 on 2022-11-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0008_writingrecord_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingrecord',
            name='score',
            field=models.IntegerField(default=-1, verbose_name='score'),
        ),
    ]
