# Generated by Django 4.0.3 on 2022-11-27 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writing', '0009_alter_writingrecord_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingassignment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='writingassignment',
            name='user',
        ),
        migrations.AddField(
            model_name='writingassignment',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='student'),
            preserve_default=False,
        ),
    ]
